In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9541, 2121, 6619, 8986],
 [9541, 2121, 6619, 8283],
 [9541, 447, 6619, 4521],
 [6933, 1801, 123, 4438, 8525],
 [6933, 1801, 123, 4438, 703],
 [3698, 9541, 9818, 6619, 3590],
 [4242, 7346, 9489, 4438]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9541 2121 6619 8986]
 [   0    0    0    0 9541 2121 6619 8283]
 [   0    0    0    0 9541  447 6619 4521]
 [   0    0    0 6933 1801  123 4438 8525]
 [   0    0    0 6933 1801  123 4438  703]
 [   0    0    0 3698 9541 9818 6619 3590]
 [   0    0    0    0 4242 7346 9489 4438]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\yassarje\Documents\AI_WORK\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


array([[[ 4.94614951e-02,  1.84724443e-02,  4.12217416e-02,
          3.30495872e-02, -3.38737518e-02,  3.13041247e-02,
          3.79456617e-02,  1.07892640e-02, -4.16387804e-02,
          3.96917015e-03],
        [ 4.94614951e-02,  1.84724443e-02,  4.12217416e-02,
          3.30495872e-02, -3.38737518e-02,  3.13041247e-02,
          3.79456617e-02,  1.07892640e-02, -4.16387804e-02,
          3.96917015e-03],
        [ 4.94614951e-02,  1.84724443e-02,  4.12217416e-02,
          3.30495872e-02, -3.38737518e-02,  3.13041247e-02,
          3.79456617e-02,  1.07892640e-02, -4.16387804e-02,
          3.96917015e-03],
        [ 4.94614951e-02,  1.84724443e-02,  4.12217416e-02,
          3.30495872e-02, -3.38737518e-02,  3.13041247e-02,
          3.79456617e-02,  1.07892640e-02, -4.16387804e-02,
          3.96917015e-03],
        [ 3.30157317e-02, -1.24166608e-02,  2.31394805e-02,
         -1.01206191e-02, -4.18125391e-02,  3.34174968e-02,
          2.82034986e-02,  3.24360393e-02, -4.678132

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9541, 2121, 6619, 8986], dtype=int32)

In [17]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step


array([[[ 0.0494615 ,  0.01847244,  0.04122174,  0.03304959,
         -0.03387375,  0.03130412,  0.03794566,  0.01078926,
         -0.04163878,  0.00396917],
        [ 0.0494615 ,  0.01847244,  0.04122174,  0.03304959,
         -0.03387375,  0.03130412,  0.03794566,  0.01078926,
         -0.04163878,  0.00396917],
        [ 0.0494615 ,  0.01847244,  0.04122174,  0.03304959,
         -0.03387375,  0.03130412,  0.03794566,  0.01078926,
         -0.04163878,  0.00396917],
        [ 0.0494615 ,  0.01847244,  0.04122174,  0.03304959,
         -0.03387375,  0.03130412,  0.03794566,  0.01078926,
         -0.04163878,  0.00396917],
        [ 0.03301573, -0.01241666,  0.02313948, -0.01012062,
         -0.04181254,  0.0334175 ,  0.0282035 ,  0.03243604,
         -0.04678133, -0.04236213],
        [-0.03074198, -0.03913004,  0.02312898,  0.02973552,
         -0.02294996, -0.01931621,  0.04922468, -0.02407682,
          0.03020461, -0.03412429],
        [ 0.04846691,  0.0197933 ,  0.02257538,  0.0